# Generated by Django 6.0 on 2026-01-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('railway', 'Railway'), ('automotive', 'Automotive'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FabricationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_minutes', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quality_score', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=50)),
                ('weight_sensitivity', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('finish_preference', models.CharField(max_length=50)),
                ('recommended_material', models.CharField(max_length=50)),
                ('reasoning', models.TextField()),
                ('tradeoffs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material', models.CharField(choices=[('aluminium', 'Aluminium'), ('stainless', 'Stainless Steel')], max_length=50)),
                ('category', models.CharField(choices=[('door', 'Door Assembly'), ('window', 'Lavatory Window'), ('panel', 'Panel/Cover'), ('loader_arm', 'Loader Arm Assembly'), ('cubical_door', 'Cubical Door Assembly')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in mm', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in mm', max_digits=6)),
                ('material', models.CharField(choices=[('aluminium', 'Aluminium'), ('stainless', 'Stainless Steel')], max_length=50)),
                ('finish', models.CharField(choices=[('brushed', 'Brushed'), ('mirror', 'Mirror'), ('bead', 'Bead-blast'), ('powder', 'Powder-coat')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pro.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.product')),
            ],
        ),
    ]
