# Generated by Django 6.0 on 2026-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('aluminium', 'Aluminium'), ('stainless', 'Stainless Steel'), ('aluminium & stainless', 'Aluminium & Stainless Steel')], max_length=50),
        ),
    ]
